FROM node:12.13.0-alpine
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN adduser -S app
COPY client/remesh_chat_react_client ./

# install app dependencies
COPY client/remesh_chat_react_client/package.json ./
COPY client/remesh_chat_react_client/package-lock.json ./
RUN npm install

RUN chown -R app /opt/app
USER app
EXPOSE 3000
CMD [ "npm", "run", "test"]
CMD [ "npm", "start" ]
