FROM node:12.13.0-alpine
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN adduser -S app
COPY server/ .
RUN npm install
RUN chown -R app /opt/app
USER app
EXPOSE 8080
# TODO: add command for script to generate test data and add to database
CMD ["npm", "run", "test"]
CMD [ "npm", "run", "pm2" ]
